// =============================================
// produits-data.js - Données de tous les produits
// =============================================

const ALL_PRODUCTS = {
    1: {
        "id": 1,
        "name": "Huile pour barbe et cheveux",
        "price": 7900,
        "oldPrice": 12000,
        "stock": 45,
        "category": "Beauté",
        "images": ["images/1.jpg"],
        "img1": "images/1.jpg",
        "img2": "images/3.jpg",
        "img3": "images/2.jpeg",
        "img4": "images/4.jpg",
        "img5": "images/5.webp",
        "img6": "images/default.jpg",
        "imgCentered": "images/5.jpg",
        "title1": "🚀 Une routine simple pour des résultats visibles !",
        "desc1": "Pas besoin de produits compliqués ! Applique quelques gouttes par jour et masse doucement. Utilisation facile et rapide, convient barbe + cheveux, adapté à tous (hommes & femmes). En quelques semaines, tu commences déjà à voir la différence ! Simple, naturel et efficace.",
        "list1": "🌿 Naturel\n💧 Hydratant\n✨ Brillance\n💪 Renforce",
        "title2": "😤 Marre de la chute de cheveux ou des zones clairsemées",
        "desc2": "Perdre ses cheveux ou ne pas avoir une barbe complète peut être frustrant… Cette huile agit directement à la racine pour réduire la chute, stimuler la repousse et combler les zones vides. Hommes ou femmes, elle s'adapte à tous les types de cheveux.",
        "list2": "🛡️ Anti-chute\n🌱 Stimule la pousse\n💆‍♂️ Facile à appliquer\n🧴 Non gras",
        "title3": "🌿 Faites pousser vos cheveux et votre barbe naturellement !",
        "desc3": "Vous avez des trous dans la barbe ou des cheveux qui ne poussent plus ? Cette huile naturelle est conçue pour stimuler la pousse et renforcer vos cheveux comme votre barbe. Grâce à ses ingrédients puissants, elle nourrit en profondeur, hydrate et active les racines.",
        "list3": "🌱 Ingrédients naturels\n💪 Résultats visibles\n🧴 Texture légère\n🌿 Parfum agréable",
        "video": "videos/vibarbe.mp4",
        "reviews": [
            { "stars": 5, "text": "J'utilise cette huile depuis 2 semaines et ma barbe est déjà plus dense et douce. Je recommande vivement !", "author": "Koffi A., Lomé" },
            { "stars": 4.5, "text": "Très bon produit, odeur agréable. Mes cheveux sont moins secs. Livraison rapide.", "author": "Nadia B., Segbé" },
            { "stars": 5, "text": "Enfin une huile qui ne fait pas graisser. Résultat visible après 3 semaines. Je rachèterai.", "author": "Esso S., Kara" },
            { "stars": 4.5, "text": "Produit de qualité. La texture est parfaite, pénètre vite. Ma barbe a gagné en épaisseur.", "author": "Jean-Marc D., Wuiti" },
            { "stars": 5, "text": "Je l'applique chaque soir sur mes cheveux. Ils sont plus brillants et tombent moins. Merci AfriCervo !", "author": "Yves K., Kisito" },
            { "stars": 4.5, "text": "Meilleure huile pour barbe testée. Fait pousser plus vite, sans irritation.", "author": "Moussa T., Dapaong" },
            { "stars": 5, "text": "Vendeur sérieux, produit conforme. L'odeur est subtile et agréable. Ravi de mon achat.", "author": "David H., Agoe" },
            { "stars": 4.5, "text": "Très bien, juste l'emballage à améliorer. L'huile est top, les résultats au rendez-vous.", "author": "Rachel M., Tsévié" },
            { "stars": 5, "text": "Ma barbe était rêche, maintenant elle est souple. Excellent rapport qualité/prix.", "author": "Adama C., Kétao" },
            { "stars": 5, "text": "Service après-vente réactif. Le produit fait ce qu'il promet. Je recommande les yeux fermés.", "author": "Elom G., Aného" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison gratuite partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours si produit non utilisé entièrement." },
            { "q": "Comment appliquer l'huile ?", "a": "Quelques gouttes sur barbe ou cheveux propres, massez délicatement." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, un numéro de suivi vous sera envoyé par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre spéciale – stock limité, réservé aux premières commandes !"
    },
    2: {
        "id": 2,
        "name": "Montre connectée SK40",
        "price": 21900,
        "oldPrice": 40000,
        "stock": 12,
        "category": "Électronique",
        "images": ["images/111.gif"],
        "img1": "images/M1.jpg",
        "img2": "images/M2.jpg",
        "img3": "images/M3.jpg",
        "img4": "images/M4.jpg",
        "img5": "images/M5.webp",
        "img6": "images/default.jpg",
        "imgCentered": "images/centree.jpg",
        "title1": "📱 Restez connecté partout",
        "desc1": "Passez et recevez vos appels directement depuis votre montre grâce à son haut-parleur et son micro intégrés. Consultez vos messages sans sortir votre téléphone.",
        "list1": "📞 Appels directs\n💬 Notifications\n📱 Écran AMOLED\n🔋 Autonomie 3 jours",
        "title2": "🎵 Une montre intelligente et pratique",
        "desc2": "Contrôlez votre musique, consultez la météo, accédez à vos contacts et profitez d'un écran AMOLED clair et moderne pour une utilisation fluide.",
        "list2": "🎵 Contrôle musique\n🌤️ Météo\n👥 Contacts\n📱 Écran tactile",
        "title3": "❤️ Suivez votre santé en temps réel",
        "desc3": "Surveillez votre fréquence cardiaque, votre taux d'oxygène dans le sang et votre sommeil en toute simplicité. Gardez un œil sur votre bien-être au quotidien.",
        "list3": "❤️ Fréquence cardiaque\n🫁 Oxygène sang\n😴 Suivi sommeil\n🏃‍♂️ Compteur pas",
        "video": "videos/222.mp4",
        "reviews": [
            { "stars": 5, "text": "Très bonne montre, l'autonomie tient bien 2 jours. Écran lumineux, livraison rapide.", "author": "Koffi A., Totsi" },
            { "stars": 4.5, "text": "Design élégant, confortable au poignet. Les notifications fonctionnent parfaitement avec mon iPhone.", "author": "Nadia B., Bassar" },
            { "stars": 5, "text": "J'ai pris le pack 2, économique. Excellente montre pour le sport, le cardiographe fiable.", "author": "Esso S., Tokoin hopital" },
            { "stars": 5, "text": "Rapport qualité/prix imbattable. Suivi du sommeil précis. La batterie dure 3 jours en usage normal.", "author": "Jean-Marc D., Kégué" },
            { "stars": 4.5, "text": "Facile à appairer, envoi des SMS et appels. L'application est simple d'utilisation.", "author": "Yves K., Atakpamé" },
            { "stars": 5, "text": "Reçue en 48h, conforme à la description. Le bracelet est agréable, l'écran tactile réactif.", "author": "Moussa T., Avédji" },
            { "stars": 5, "text": "Très content de mon achat. Elle a remplacé ma vieille Fitbit. Suivi du stress en plus.", "author": "David H., Agoe" },
            { "stars": 4.5, "text": "Bon rapport qualité/prix. Le seul bémol : l'application parfois en anglais, mais ça va.", "author": "Rachel M., Ségbé" },
            { "stars": 5, "text": "Je l'utilise tous les jours. Étanche, je peux me laver les mains sans l'enlever.", "author": "Adama C., Kpalimé" },
            { "stars": 5, "text": "Excellent service après-vente. Ils m'ont contacté pour confirmer la commande. Montre au top.", "author": "Elom G., Agbodrafo" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison gratuite partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours si produit non utilisé entièrement." },
            { "q": "Comment utiliser la montre ?", "a": "Chargez-la, associez via Bluetooth à l'application dédiée." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, un numéro de suivi vous sera envoyé par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre spéciale – stock limité, réservé aux premières commandes !"
    },
    3: {
        "id": 3,
        "name": "Montre connectée A58 plus",
        "price": 11900,
        "oldPrice": 22000,
        "stock": 15,
        "category": "Électronique",
        "images": ["images/A58.jpg"],
        "img1": "images/A581.jpg",
        "img2": "images/A582.jpg",
        "img3": "images/A583.jpg",
        "img4": "images/A585.jpg",
        "img5": "images/A585.webp",
        "img6": "images/default.jpg",
        "imgCentered": "images/A586.jpg",
        "title1": "🎁 Le cadeau parfait qui fait vraiment plaisir !",
        "desc1": "Vous cherchez un cadeau utile et impressionnant ? Ce coffret design avec accessoires inclus est idéal pour toutes les occasions.",
        "list1": "🎁 Coffret complet\n⌚ Montre connectée\n💎 Bijoux assortis\n📦 Emballage cadeau",
        "title2": "📲 Restez connecté(e) avec classe !",
        "desc2": "Ce n'est pas qu'une montre, c'est votre assistant personnel au poignet. Passez des appels, recevez vos notifications, suivez votre santé.",
        "list2": "📞 Appels\n💬 Notifications\n❤️ Santé\n🎵 Musique",
        "title3": "✨ Un seul coffret, tout votre style est assuré !",
        "desc3": "Pourquoi acheter séparément quand vous pouvez tout avoir en un seul pack ? Montre connectée, montre classique dorée et bijoux assortis.",
        "list3": "⌚ Montre connectée\n💛 Montre dorée\n💎 Bijoux assortis\n🎁 Cadeau idéal",
        "video": "videos/A580.mp4",
        "reviews": [
            { "stars": 5, "text": "Le coffret complet est bluffant. J'ai reçu montre + bijoux assortis. Très belle surprise.", "author": "Koffi A., Tokoin forever" },
            { "stars": 4.5, "text": "La montre connectée est très pratique. Les bracelets supplémentaires sont élégants. Idéal pour offrir.", "author": "Nadia B., Kara" },
            { "stars": 5, "text": "Livraison en 48h, emballage soigné. La qualité est au rendez-vous. Je l'ai déjà recommandée.", "author": "Esso S., Akodessewa" },
            { "stars": 5, "text": "Parfait pour les femmes qui aiment changer de style. La montre classique dorée fait son effet.", "author": "Jean-Marc D., Sokodé" },
            { "stars": 4.5, "text": "Rappel des appels et messages très utile. Le boîtier est léger. Bonne autonomie.", "author": "Yves K., Kpalimé" },
            { "stars": 5, "text": "Un cadeau parfait pour ma femme. Elle adore les bijoux assortis. Merci AfriCervo.", "author": "Moussa T., Agbalepedo" },
            { "stars": 5, "text": "Très bon produit, l'écran est net. Le logiciel de suivi d'activité est complet.", "author": "David H., Saint Joseph" },
            { "stars": 4.5, "text": "Très belle montre, juste dommage que la notice soit en plusieurs langues, mais ça va.", "author": "Rachel M., Cinkassé" },
            { "stars": 5, "text": "Un style unique, tout le monde me demande où je l'ai achetée. Très satisfait.", "author": "Adama C., Kpalimé" },
            { "stars": 5, "text": "Super service, livraison rapide. La montre tient ses promesses. Le suivi client est sérieux.", "author": "Elom G., Baguida" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours si produit non utilisé entièrement." },
            { "q": "Comment utiliser la montre ?", "a": "Chargez-la, associez via Bluetooth à l'application dédiée." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, un numéro de suivi vous sera envoyé par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre spéciale – stock limité, réservé aux premières commandes !"
    },
    4: {
        "id": 4,
        "name": "Diffuseur H2O",
        "price": 9900,
        "oldPrice": 18000,
        "stock": 28,
        "category": "Maison",
        "images": ["images/diffuseur.jpg"],
        "img1": "images/dif1.jpg",
        "img2": "images/dif2.jpg",
        "img3": "images/dif3.jpg",
        "img4": "images/dif4.jpg",
        "img5": "images/dif5.webp",
        "img6": "images/default.jpg",
        "imgCentered": "images/dif5.jpg",
        "title1": "🌿 Transformez votre espace en un havre de détente !",
        "desc1": "Fatigué du stress quotidien et de l'air sec ? Ajoutez quelques gouttes d'huile essentielle et laissez la magie opérer. Détente totale et bien-être assuré.",
        "list1": "🌿 Atmosphère apaisante\n💧 Brume légère et lumière douce\n😌 Détente totale\n😴 Sommeil amélioré",
        "title2": "😤 Marre de la chaleur et de l'air étouffant ?",
        "desc2": "Entre la chaleur et l'air sec, rester à l'aise chez soi devient difficile. Ce mini humidificateur hydrate l'air et rend votre espace agréable.",
        "list2": "💨 Rafraîchit votre environnement\n💧 Hydrate l'air naturellement\n🫁 Respirez mieux\n😊 Vivez mieux au quotidien",
        "title3": "💡 Un appareil simple pour un confort maximal !",
        "desc3": "Compact, élégant et facile à utiliser, ce diffuseur s'adapte partout : chambre, bureau, salon. Branchez et profitez instantanément.",
        "list3": "🔇 Brume silencieuse jour et nuit\n💡 Lumière LED relaxante\n🔋 Recharge USB pratique\n🏡 Transforme instantanément votre espace",
        "video": "videos/dif0.mp4",
        "reviews": [
            { "stars": 5, "text": "Excellent diffuseur, très silencieux. J'y mets de l'huile essentielle de lavande, toute la maison est apaisée.", "author": "Koffi A., Limosine" },
            { "stars": 4.5, "text": "Les lumières LED sont magnifiques, 7 couleurs différentes. Mon enfant adore s'endormir avec.", "author": "Nadia B., Adéwui" },
            { "stars": 5, "text": "Prend peu de place, design moderne. La brume est fine, l'autonomie d'eau est correcte (environ 6h).", "author": "Esso S., Kouka" },
            { "stars": 5, "text": "Idéal pour le bureau, il me permet de me détendre pendant les pauses. Qualité irréprochable.", "author": "Jean-Marc D., Tabligbo" },
            { "stars": 4.5, "text": "Très bonne autonomie, recharge USB pratique. La minuterie automatique est un plus.", "author": "Yves K., Notse" },
            { "stars": 5, "text": "J'ai pris le pack 2, un à la maison, un au bureau. Relaxation assurée.", "author": "Moussa T., Dapaong" },
            { "stars": 5, "text": "Mon cadeau préféré de Noël. Le diffuseur fonctionne parfaitement après plusieurs mois.", "author": "David H., Cacavéli" },
            { "stars": 4.5, "text": "Très bien, juste l'emballage à améliorer (un peu écrasé). Le produit est top.", "author": "Rachel M., Anié" },
            { "stars": 5, "text": "Excellent rapport qualité/prix. Le flux de vapeur peut être réglé. Je recommande.", "author": "Adama C., Kpalimé" },
            { "stars": 5, "text": "Super service après-vente, ils m'ont rappelé pour confirmer la commande. Très professionnel.", "author": "Elom G., Adidogomé" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours." },
            { "q": "Comment utiliser le diffuseur ?", "a": "Remplissez d'eau, ajoutez quelques gouttes d'huile essentielle, allumez." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, suivi par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre exclusive – stock limité, réservé aux premières commandes !"
    },
    5: {
        "id": 5,
        "name": "Lime électrique",
        "price": 10500,
        "oldPrice": 19000,
        "stock": 8,
        "category": "Beauté",
        "images": ["images/lim1.jpg"],
        "img1": "images/lim1.jpg",
        "img2": "images/lim2.jpg",
        "img3": "images/lim3.jpg",
        "img4": "images/lim4.jpg",
        "img5": "images/lim5.webp",
        "img6": "images/default.jpg",
        "imgCentered": "images/lim5.jpg",
        "title1": "🔥 Des pieds doux et lisses en quelques minutes !",
        "desc1": "Vous en avez assez des talons secs, craquelés ou rugueux ? Cette lime électrique élimine facilement les peaux mortes pour des pieds impeccables.",
        "list1": "🦶 Élimine les peaux mortes\n✨ Pieds doux et lisses\n⚡ Rapide et efficace\n💅 Soin professionnel à domicile",
        "title2": "😣 Stop aux pieds négligés qui vous gênent !",
        "desc2": "Les pieds abîmés peuvent vite devenir un complexe. Cette pédicure électrique agit rapidement et sans douleur pour éliminer les callosités.",
        "list2": "🛑 Adieu les callosités\n🦶 Pédicure sans douleur\n⚡ Action rapide\n😊 Retrouvez confiance",
        "title3": "🚀 Votre pédicure professionnelle à domicile !",
        "desc3": "Plus besoin de dépenser chaque semaine en institut. Simple, rapide et efficace, cet appareil rechargeable prend soin de vos pieds à tout moment.",
        "list3": "🏠 Soin à domicile\n🔋 Rechargeable\n💰 Économique\n⏰ Gain de temps",
        "video": "videos/lim0.mp4",
        "reviews": [
            { "stars": 5, "text": "Très bonne lime électrique, les embouts sont de qualité. Mes pieds n'ont jamais été aussi doux.", "author": "Koffi A., Attiegou" },
            { "stars": 4.5, "text": "Pratique pour entretenir les ongles à la maison. Je recommande vivement.", "author": "Nadia B., Cotonou" },
            { "stars": 5, "text": "J'ai pris le pack 2, une pour moi, une pour offrir à ma mère. Très contente. Livraison rapide.", "author": "Esso S., Kanté" },
            { "stars": 5, "text": "Silencieuse et efficace, rien à redire. Les 6 embouts sont très utiles.", "author": "Jean-Marc D., Sokodé" },
            { "stars": 4.5, "text": "Bonne autonomie, je l'utilise depuis 2 mois sans problème. La batterie tient bien.", "author": "Yves K., Atakpamé" },
            { "stars": 5, "text": "Meilleur achat pour mes soins des pieds. Fini les corne douloureuses.", "author": "Moussa T., Sagbado" },
            { "stars": 5, "text": "Le vendeur est sérieux, produit conforme. La lime est robuste et facile à nettoyer.", "author": "David H., Hédzranawoé" },
            { "stars": 4.5, "text": "Très bien, juste l'emballage à améliorer. L'appareil fait le boulot parfaitement.", "author": "Rachel M., Adétikopé" },
            { "stars": 5, "text": "Excellent rapport qualité/prix. Je l'emporte en voyage grâce à sa petite taille.", "author": "Adama C., Kpalimé" },
            { "stars": 5, "text": "Super service après-vente, ils m'ont appelé pour confirmer. Sérieux et efficace.", "author": "Elom G., Kpogan" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours." },
            { "q": "Comment utiliser la lime ?", "a": "Choisissez l'embout adapté, appuyez doucement sur l'ongle." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, suivi par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre exclusive – stock limité, réservé aux premières commandes !"
    },
    6: {
        "id": 6,
        "name": "Montre connectée H92 Ultra3",
        "price": 10900,
        "oldPrice": 19000,
        "stock": 10,
        "category": "Électronique",
        "images": ["images/H92.jpg"],
        "img1": "images/H1.jpg",
        "img2": "images/H2.jpg",
        "img3": "images/H3.jpg",
        "img4": "images/H4.jpg",
        "img5": "images/H5.jpg",
        "img6": "images/default.jpg",
        "imgCentered": "images/H5.jpg",
        "title1": "📲 Restez connecté partout avec la H92 Ultra 3 !",
        "desc1": "La montre connectée H92 Ultra 3 vous permet de rester connecté sans sortir votre téléphone. Design moderne et écran ultra élégant.",
        "list1": "📞 Appels directs\n💬 Notifications\n📱 Écran tactile\n🔋 Autonomie 5 jours",
        "title2": "❤️ Prenez soin de votre santé au quotidien !",
        "desc2": "La H92 Ultra 3 ne fait pas que donner l'heure, elle vous accompagne chaque jour. Surveillez votre cœur, votre sommeil et vos activités.",
        "list2": "❤️ Fréquence cardiaque\n😴 Suivi du sommeil\n🏃‍♂️ Compteur de pas\n🫁 Oxygène sang",
        "title3": "🎁 Un coffret ultra complet avec plusieurs bracelets !",
        "desc3": "Ce pack H92 Ultra 3 est livré avec plusieurs accessoires pour changer de style selon vos envies. Élégance, technologie et polyvalence.",
        "list3": "⌚ Montre connectée\n🎨 Bracelets interchangeables\n📦 Coffret complet\n💎 Design élégant",
        "video": "videos/H.mp4",
        "reviews": [
            { "stars": 5, "text": "Très bonne montre, l'écran est grand et lisible. Le cardio est précis. Je suis ravi.", "author": "Koffi A., Lomé" },
            { "stars": 4.5, "text": "Suivi du sommeil intéressant. Le bracelet est confortable. Autonomie 5 jours.", "author": "Nadia B., Djidjolé" },
            { "stars": 5, "text": "Reçue en 48h, conforme à la description. Application intuitive. Très bon rapport qualité-prix.", "author": "Esso S., Mango" },
            { "stars": 5, "text": "Idéale pour le sport : compteur de pas, calories, distance. Top !", "author": "Jean-Marc D., Sotouboua" },
            { "stars": 4.5, "text": "Très bien, écran tactile réactif. Les notifications arrivent bien.", "author": "Yves K., Gbossimé" },
            { "stars": 5, "text": "Ma première montre connectée. Très facile à configurer.", "author": "Moussa T., 2 lions" },
            { "stars": 5, "text": "Je l'ai offerte à mon père, il l'adore. La batterie dure plus d'une semaine.", "author": "David H., Assivito" },
            { "stars": 4.5, "text": "Design sobre, passe partout. Seul petit défaut : la luminosité en extérieur.", "author": "Rachel M., Davié" },
            { "stars": 5, "text": "Excellente montre pour le prix. Toutes les fonctionnalités de base sont présentes.", "author": "Adama C., Bafilo" },
            { "stars": 5, "text": "Service client réactif. La montre a été livrée rapidement. Très content.", "author": "Elom G., Kpogan" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours." },
            { "q": "Comment utiliser la montre ?", "a": "Chargez-la, associez via Bluetooth à l'application dédiée." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, suivi par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre exclusive – stock limité, réservé aux premières commandes !"
    },
    7: {
        "id": 7,
        "name": "Mixeur de jus portable",
        "price": 9900,
        "oldPrice": 18000,
        "stock": 20,
        "category": "Maison",
        "images": ["images/jus.jpg"],
        "img1": "images/jus1.jpg",
        "img2": "images/jus2.jpg",
        "img3": "images/jus3.jpg",
        "img4": "images/jus4.jpg",
        "img5": "images/jus5.jpg",
        "img6": "images/default.jpg",
        "imgCentered": "images/jus5.jpg",
        "title1": "🍓 Préparez vos boissons préférées partout !",
        "desc1": "Envie d'un smoothie frais ou d'un jus naturel en quelques secondes ? Ce mini blender portable est votre compagnon idéal pour des boissons saines.",
        "list1": "🍓 Smoothies frais\n⚡ Mixage rapide\n🔋 Autonomie 15 pressages\n🧼 Nettoyage facile",
        "title2": "⚡ Le blender portable qui simplifie votre quotidien !",
        "desc2": "Plus besoin de gros appareils encombrants. Ses lames puissantes mixent efficacement en quelques secondes. Mangez plus sainement sans complication.",
        "list2": "⚡ Lames puissantes\n⏱️ Mixage en secondes\n🥤 Boissons saines\n🧼 Facile à nettoyer",
        "title3": "🌿 Petit format, grandes performances !",
        "desc3": "Ne vous fiez pas à sa taille, ce mini blender est ultra pratique et puissant. Léger, transportable et facile à nettoyer pour une utilisation quotidienne.",
        "list3": "📏 Compact\n💪 Puissant\n🧳 Transportable\n♻️ Rechargeable",
        "video": "videos/jus.mp4",
        "reviews": [
            { "stars": 5, "text": "Très pratique, je l'emporte partout. Jus délicieux et rapide. Nettoyage facile.", "author": "Koffi A., Agodekè" },
            { "stars": 4.5, "text": "Bonne autonomie, se nettoie facilement. Les lames en acier inoxydable sont efficaces.", "author": "Nadia B., Adidogomé" },
            { "stars": 5, "text": "Le format compact est parfait pour mon bureau. Je mixe smoothies et soupes.", "author": "Esso S., Bè" },
            { "stars": 5, "text": "Un excellent produit, je recommande. La batterie tient plusieurs jus.", "author": "Jean-Marc D., Agoe" },
            { "stars": 4.5, "text": "Rapide et efficace, aucun bruit gênant. Attention aux gros morceaux.", "author": "Yves K., Atakpamé" },
            { "stars": 5, "text": "Idéal pour les smoothies. Livraison rapide.", "author": "Moussa T., Dapaong" },
            { "stars": 5, "text": "Le plastique est solide, très content. Le bouchon étanche évite les fuites.", "author": "David H., Tokoin-wuiti" },
            { "stars": 4.5, "text": "Batterie tient bien, environ 15 pressages.", "author": "Rachel M., Doumassessé" },
            { "stars": 5, "text": "Rapport qualité/prix imbattable. Je l'utilise pour mes protéines.", "author": "Adama C., Adidoadin" },
            { "stars": 5, "text": "Satisfait, comme sur la description. Service client sérieux.", "author": "Elom G., Aného" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours." },
            { "q": "Comment utiliser l'extracteur ?", "a": "Chargez, coupez les fruits, mixez directement dans le gobelet." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, suivi par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre exclusive – stock limité, réservé aux premières commandes !"
    },
    8: {
        "id": 8,
        "name": "Coupe legume multifonction",
        "price": 12000,
        "oldPrice": 22000,
        "stock": 18,
        "category": "Maison",
        "images": ["images/coup1.jpg"],
        "img1": "images/coup1.jpg",
        "img2": "images/coup2.jpg",
        "img3": "images/coup3.jpg",
        "img4": "images/coup4.jpg",
        "img5": "images/coup5.jpg",
        "img6": "images/default.jpg",
        "imgCentered": "images/coup5.jpg",
        "title1": "🔪 Coupez, tranchez et râpez en quelques secondes !",
        "desc1": "Fatigué de passer trop de temps à couper les légumes en cuisine ? Ce coupe-légumes multifonction rend tout plus simple, rapide et sans effort.",
        "list1": "🔪 Coupe rapide\n🥕 Lames interchangeables\n⏱️ Gain de temps\n🧼 Facile à nettoyer",
        "title2": "⚡ La solution pratique pour une cuisine rapide et propre !",
        "desc2": "Plus besoin de plusieurs outils encombrants. Lames interchangeables, découpe précise et bac de récupération intégré pour cuisiner sans stress.",
        "list2": "⚡ Découpe précise\n🥗 Bac de récupération\n🔪 Lames interchangeables\n🧼 Nettoyage facile",
        "title3": "🥗 Préparez vos repas sans stress !",
        "desc3": "Avec ce coupe-légumes multifonction, cuisiner devient un vrai plaisir. Compact, pratique et ultra efficace pour des repas faits maison.",
        "list3": "📏 Compact\n⚡ Ultra efficace\n🔪 Lames de qualité\n🍽️ Repas faits maison",
        "video": "videos/coup.mp4",
        "reviews": [
            { "stars": 5, "text": "Excellent hachoir, je l'utilise tous les jours. Hache oignons, ail, légumes en un rien de temps.", "author": "Koffi A., Lomé" },
            { "stars": 4.5, "text": "Puissant et facile à nettoyer. Les lames se démontent facilement.", "author": "Nadia B., Zanguera" },
            { "stars": 5, "text": "Parfait pour hacher les oignons sans pleurer. Gain de temps assuré.", "author": "Esso S., Kara" },
            { "stars": 5, "text": "Bonne autonomie, je recommande. J'ai haché de la viande crue.", "author": "Jean-Marc D., Bassar" },
            { "stars": 4.5, "text": "Compact et efficace. Livraison rapide.", "author": "Yves K., Tokoin ramco" },
            { "stars": 5, "text": "Livraison rapide, produit conforme. Je l'utilise pour mes repas de sportif.", "author": "Moussa T., Djablé" },
            { "stars": 5, "text": "Très content de mon achat. Il remplace mon vieux robot.", "author": "David H., Lomegan" },
            { "stars": 4.5, "text": "Un bon rapport qualité/prix. Le câble USB est long.", "author": "Rachel M., Adéticopé" },
            { "stars": 5, "text": "J'ai pris le pack 2, un pour offrir à ma sœur. Elle est ravie.", "author": "Adama C., Kpogan" },
            { "stars": 5, "text": "Service client réactif. Le hachoir est robuste.", "author": "Elom G., Atikoumé" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours." },
            { "q": "Nettoyage ?", "a": "Rincez sous l'eau, lames amovibles." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, suivi par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre exclusive – stock limité, réservé aux premières commandes !"
    },
    9: {
        "id": 9,
        "name": "Anti-tache et Acné",
        "price": 7100,
        "oldPrice": 12000,
        "stock": 30,
        "category": "Beauté",
        "images": ["images/visage.jpg"],
        "img1": "images/mas1.gif",
        "img2": "images/mas2.jpg",
        "img3": "images/mas3.gif",
        "img4": "images/mas4.jpg",
        "img5": "images/mas5.jpg",
        "img6": "images/default.jpg",
        "imgCentered": "images/mas5.jpg",
        "title1": "🌿 Dites adieu aux boutons et retrouvez une peau nette !",
        "desc1": "Les boutons, les taches et l'excès de graisse peuvent ruiner votre confiance. Grâce au Green Mask Stick, nettoyez votre peau en profondeur.",
        "list1": "🌿 Nettoie en profondeur\n💧 Réduit l'excès de sébum\n✨ Peau nette\n😍 Retrouvez confiance",
        "title2": "😍 Une peau lisse et éclatante sans effort !",
        "desc2": "Prenez enfin soin de votre visage avec un masque pratique et facile à utiliser. Sa formule aide à purifier la peau, contrôler l'excès de sébum.",
        "list2": "😍 Peau lisse\n💧 Purifie\n✨ Éclatant\n🧴 Facile à appliquer",
        "title3": "⚡ Le soin visage simple que tout le monde adopte !",
        "desc3": "Plus besoin de routines compliquées ou de produits difficiles à appliquer. Format stick pratique, application rapide et propre.",
        "list3": "⚡ Application rapide\n🧴 Format stick\n✨ Résultats visibles\n💧 Peau nette",
        "video": "videos/mas.mp4",
        "reviews": [
            { "stars": 5, "text": "Incroyable, mes taches d'acné ont beaucoup diminué en 2 semaines.", "author": "Koffi A., Legbassito" },
            { "stars": 4.5, "text": "Bonne crème, ma peau est plus nette.", "author": "Nadia B., Klikamé" },
            { "stars": 5, "text": "Efficace contre les cicatrices d'acné. J'ai repris confiance en moi.", "author": "Esso S., Kouka" },
            { "stars": 5, "text": "Je recommande, très bon rapport qualité/prix.", "author": "Jean-Marc D., Cassablamca" },
            { "stars": 4.5, "text": "Odeur agréable, ne colle pas. Utilisation matin et soir.", "author": "Yves K., Adéwui" },
            { "stars": 5, "text": "Résultat après 2 semaines. Mes taches brunes s'estompent.", "author": "Moussa T., Agoe" },
            { "stars": 5, "text": "Parfait pour les peaux mixtes et grasses.", "author": "David H., Baguida" },
            { "stars": 4.5, "text": "Très bien, je rachèterai. Dommage que le tube soit un peu petit.", "author": "Rachel M., Ségbé" },
            { "stars": 5, "text": "Unifie mon teint en douceur.", "author": "Adama C., Vogan" },
            { "stars": 5, "text": "Exactement ce qu'il me fallait. Service client sérieux.", "author": "Elom G., Kpogan" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours." },
            { "q": "Comment utiliser ?", "a": "Appliquer matin et soir sur peau propre." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, suivi par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre exclusive – stock limité, réservé aux premières commandes !"
    },
    10: {
        "id": 10,
        "name": "Mandoline multifonction",
        "price": 12000,
        "oldPrice": 22000,
        "stock": 15,
        "category": "Maison",
        "images": ["images/man1.jpg"],
        "img1": "images/man1.jpg",
        "img2": "images/man2.jpg",
        "img3": "images/man3.jpg",
        "img4": "images/man4.jpg",
        "img5": "images/man5.jpg",
        "img6": "images/default.jpg",
        "imgCentered": "images/man5.jpg",
        "title1": "🔪 Coupez vos légumes comme un chef en quelques secondes !",
        "desc1": "Fatigué de perdre du temps à découper les légumes à la main ? Avec cette mandoline multifonction, préparez vos repas rapidement et facilement.",
        "list1": "🔪 Découpe rapide\n🥕 Lames interchangeables\n⏱️ Gain de temps\n🧼 Facile à nettoyer",
        "title2": "⚡ La mandoline qui rend la cuisine plus simple !",
        "desc2": "Plus besoin de couteaux compliqués ou de longues préparations. Découpe rapide et uniforme, plusieurs lames interchangeables.",
        "list2": "⚡ Découpe uniforme\n🔪 Lames interchangeables\n🥗 Préparation rapide\n🧼 Nettoyage facile",
        "title3": "🥗 L'outil indispensable pour une cuisine rapide et propre !",
        "desc3": "Cette mandoline multifonction transforme votre manière de cuisiner. Compacte, pratique et facile à ranger.",
        "list3": "📏 Compacte\n🔪 8 fonctions\n🥗 Cuisine rapide\n🧼 Facile à ranger",
        "video": "videos/man.mp4",
        "reviews": [
            { "stars": 5, "text": "Très pratique, je l'utilise quotidiennement. Les 8 fonctions sont vraiment utiles.", "author": "Koffi A., Kodjoviakopé" },
            { "stars": 4.5, "text": "Gagne énormément de temps en cuisine. Les 3 bols sont parfaits.", "author": "Nadia B., Cacavéli" },
            { "stars": 5, "text": "Puissant et facile à nettoyer. Les lames sont très résistantes.", "author": "Esso S., Kara" },
            { "stars": 5, "text": "Rapport qualité/prix excellent. Idéal pour les repas de bébés.", "author": "Jean-Marc D., Zongo" },
            { "stars": 4.5, "text": "Livraison rapide, conforme à la description.", "author": "Yves K., Hédzranawoé" },
            { "stars": 5, "text": "Je recommande ce produit. Il hache la viande en 5 secondes.", "author": "Moussa T., Sogbossito" },
            { "stars": 5, "text": "Je l'offre souvent en cadeau. Tout le monde en est ravi.", "author": "David H., Nukafu" },
            { "stars": 4.5, "text": "Très bien, juste le bruit un peu fort à pleine vitesse.", "author": "Rachel M., Tsévié" },
            { "stars": 5, "text": "Un indispensable en cuisine. Je n'utilise plus que lui.", "author": "Adama C., Totsi" },
            { "stars": 5, "text": "Je l'ai pris en pack 2, un pour moi, un pour ma belle-mère.", "author": "Elom G., Aného" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours." },
            { "q": "Lames amovibles ?", "a": "Oui, les lames se retirent facilement pour le nettoyage." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, suivi par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre exclusive – stock limité, réservé aux premières commandes !"
    },
    11: {
        "id": 11,
        "name": "Patch Detox Kinoki",
        "price": 7900,
        "oldPrice": 13000,
        "stock": 25,
        "category": "Santé",
        "images": ["images/Detox.jpg"],
        "img1": "images/Detox1.jpg",
        "img2": "images/Detox2.jpg",
        "img3": "images/Detox3.jpg",
        "img4": "images/Detox4.jpg",
        "img5": "images/Detox5.jpg",
        "img6": "images/default.jpg",
        "imgCentered": "images/Detox5.jpg",
        "title1": "💪 Finis les jambes gonflées et les pieds douloureux",
        "desc1": "Chaque soir, vos pieds vous hurlent leur fatigue. Kinoki agit pendant votre sommeil pour éliminer les toxines et soulager vos jambes naturellement.",
        "list1": "💪 Soulage les jambes\n👣 Élimine les toxines\n😴 Agit pendant le sommeil\n✨ Résultats visibles",
        "title2": "👣 La preuve visuelle que Kinoki fonctionne",
        "desc2": "Contrairement aux compléments qu'on avale sans voir l'effet, Kinoki vous donne une preuve physique chaque matin. Plus le patch est foncé, plus votre corps avait besoin d'éliminer.",
        "list2": "👣 Preuve visuelle\n🌿 Détox naturelle\n😴 Sommeil réparateur\n🦵 Jambes légères",
        "title3": "🌿 Pourquoi vous traînez une fatigue constante ?",
        "desc3": "Vous avez tout essayé : café, vitamines, sport… mais le coup de barre revient chaque après-midi. Le vrai coupable ? L'auto-intoxication silencieuse.",
        "list3": "🌿 Détox profonde\n⚡ Énergie retrouvée\n😴 Meilleur sommeil\n🦵 Jambes légères",
        "video": "videos/Detox.mp4",
        "reviews": [
            { "stars": 5, "text": "Après une semaine d'utilisation, mes jambes sont beaucoup moins gonflées.", "author": "Koffi A., Avédji" },
            { "stars": 4.5, "text": "Le patch noirci vraiment ! Je sens que mon corps évacue ce qu'il n'utilise pas.", "author": "Nadia B., Nukafu" },
            { "stars": 5, "text": "Je dormais mal à cause des pieds lourds. Kinoki m'a changé la vie.", "author": "Esso S., Kara" },
            { "stars": 5, "text": "La fatigue a diminué dès la 3ème nuit. Mes chevilles ne gonflent plus.", "author": "Jean-Marc D., Sokodé" },
            { "stars": 4.5, "text": "Très efficace contre la rétention d'eau. Le pack 2 est économique.", "author": "Yves K., Ségbé" },
            { "stars": 5, "text": "Mes douleurs de pieds ont diminué. La preuve visuelle est bluffante.", "author": "Moussa T., Agbalepédo" },
            { "stars": 5, "text": "J'offre ces patchs à mes parents. Ils sont ravis.", "author": "David H., Tokoin protestant" },
            { "stars": 4.5, "text": "Très contente. Mes nuits sont plus reposantes.", "author": "Rachel M., Tsévié" },
            { "stars": 5, "text": "Pack économique imbattable. J'ai pris 2 boîtes.", "author": "Adama C., Kpalimé" },
            { "stars": 5, "text": "Je rachèterai sans hésiter. Résultats visibles en 7 jours.", "author": "Elom G., Baguida" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours." },
            { "q": "Peut-on utiliser les patchs tous les jours ?", "a": "Oui, utilisation quotidienne recommandée pour une détox en profondeur." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, suivi par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre exclusive – stock limité, réservé aux premières commandes !"
    },
    12: {
        "id": 12,
        "name": "Ecouteur intelligent M6",
        "price": 10000,
        "oldPrice": 18500,
        "stock": 18,
        "category": "Électronique",
        "images": ["images/m6.jpg"],
        "img1": "images/m61.jpg",
        "img2": "images/m62.jpg",
        "img3": "images/m63.jpg",
        "img4": "images/m64.jpg",
        "img5": "images/m65.jpg",
        "img6": "images/default.jpg",
        "imgCentered": "images/m65.jpg",
        "title1": "📞 Gérez tout sans sortir votre téléphone !",
        "desc1": "Avec les écouteurs Bluetooth M6, tout devient plus simple. Son immersif, réduction de bruit et commandes tactiles pour une expérience audio professionnelle.",
        "list1": "📞 Commandes tactiles\n🎵 Son immersif\n🔊 Réduction de bruit\n🔋 Autonomie 30h",
        "title2": "🎧 Un vrai écran intelligent dans votre poche !",
        "desc2": "Découvrez les écouteurs M6 avec écran tactile intégré sur le boîtier. Contrôlez volume, musique et appels sans toucher votre téléphone.",
        "list2": "🎧 Écran tactile\n📞 Appels sans téléphone\n🎵 Contrôle musique\n🔋 Autonomie 30h",
        "title3": "🔋 Une autonomie impressionnante toute la journée !",
        "desc3": "Marre des écouteurs qui se déchargent rapidement ? Les M6 offrent une autonomie record et des modes audio personnalisables pour tous vos usages.",
        "list3": "🔋 Autonomie 30h\n🎵 Modes audio\n📞 Appels clairs\n💧 Étanche IP7",
        "video": "videos/m6.mp4",
        "reviews": [
            { "stars": 5, "text": "Excellent son, très bonne autonomie. Les basses sont présentes.", "author": "Koffi A., Lomé" },
            { "stars": 4.5, "text": "Confortables, ne tombent pas pendant le sport.", "author": "Nadia B., Cotonou" },
            { "stars": 5, "text": "J'ai pris le pack 2, économique. Le boîtier de charge est compact.", "author": "Esso S., Kara" },
            { "stars": 5, "text": "Livraison rapide, je recommande. L'étanchéité IP7 est un vrai plus.", "author": "Jean-Marc D., Sokodé" },
            { "stars": 4.5, "text": "Bonne qualité prix. Les commandes tactiles sont réactives.", "author": "Yves K., Atakpamé" },
            { "stars": 5, "text": "Batterie tient bien, environ 30h avec le boîtier.", "author": "Moussa T., Dapaong" },
            { "stars": 5, "text": "Bluetooth stable, se couple instantanément.", "author": "David H., Lomé" },
            { "stars": 4.5, "text": "Très content. Seul défaut : les micros un peu faibles.", "author": "Rachel M., Tsévié" },
            { "stars": 5, "text": "Pack économique intéressant. Un pour moi, un pour mon conjoint.", "author": "Adama C., Kpalimé" },
            { "stars": 5, "text": "Service client réactif. Les écouteurs sont conformes.", "author": "Elom G., Aného" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison gratuite partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours." },
            { "q": "Compatibles iPhone/Android ?", "a": "Oui, tous les appareils Bluetooth." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, suivi par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre exclusive – stock limité, réservé aux premières commandes !"
    },
    13: {
        "id": 13,
        "name": "Ceinture anti-douleurs menstruelles",
        "price": 10500,
        "oldPrice": 18000,
        "stock": 12,
        "category": "Santé",
        "images": ["images/ceint.jpg"],
        "img1": "images/ceint1.jpg",
        "img2": "images/ceint2.jpg",
        "img3": "images/ceint3.jpg",
        "img4": "images/ceint4.jpg",
        "img5": "images/ceint5.jpg",
        "img6": "images/default.jpg",
        "imgCentered": "images/ceint5.jpg",
        "title1": "🩸 Finis les crampes et les douleurs abdominales",
        "desc1": "Chaque mois, les douleurs menstruelles peuvent devenir un véritable calvaire. Cette ceinture chauffante vous offre un soulagement naturel et immédiat.",
        "list1": "🩸 Soulage les crampes\n🔥 Chaleur apaisante\n🌸 Naturelle\n💖 Bien-être immédiat",
        "title2": "🌸 Une solution naturelle sans médicaments",
        "desc2": "Fini les cachets anti-douleur qui agressent votre estomac. Cette ceinture agit par chaleur infrarouge profonde pour un bien-être immédiat.",
        "list2": "🌸 Sans médicaments\n🔥 Chaleur infrarouge\n💖 Bien-être immédiat\n🩸 Soulage les crampes",
        "title3": "💖 Retrouvez votre bien-être au quotidien",
        "desc3": "Ne laissez plus les douleurs menstruelles dicter votre vie. Cette ceinture a été pensée pour vous accompagner chaque mois en toute sérénité.",
        "list3": "💖 Bien-être quotidien\n🩸 Soulage les douleurs\n🔥 Chaleur apaisante\n🌸 Naturelle",
        "video": "videos/ceint.mp4",
        "reviews": [
            { "stars": 5, "text": "Je ne peux plus m'en passer ! Mes douleurs ont diminué de 80%.", "author": "Maman de Famille A., Lomé" },
            { "stars": 4.5, "text": "Discrète et efficace. Je la porte sous mon pull au travail.", "author": "Amira B., Cotonou" },
            { "stars": 5, "text": "Je l'ai offerte à ma fille, elle ne la quitte plus.", "author": "Fatou S., Kara" },
            { "stars": 5, "text": "Livraison rapide. Le massage vibratoire est très agréable.", "author": "Grace D., Sokodé" },
            { "stars": 4.5, "text": "Très bonne ceinture, la télécommande est pratique.", "author": "Awa K., Atakpamé" },
            { "stars": 5, "text": "Pack économique, j'en ai pris une pour moi, une pour ma sœur.", "author": "Safia T., Dapaong" },
            { "stars": 5, "text": "Je la mets dès les premiers signes, les crampes s'estompent en 15 min.", "author": "Blandine H., Lomé" },
            { "stars": 4.5, "text": "Confortable, ne gratte pas. Trois niveaux de chaleur.", "author": "Clarisse M., Tsévié" },
            { "stars": 5, "text": "Idéale pour les règles douloureuses. Service client sérieux.", "author": "Rachel C., Kpalimé" },
            { "stars": 5, "text": "Je rachèterai pour offrir à ma belle-sœur.", "author": "Lucienne G., Aného" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison gratuite partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours." },
            { "q": "Comment utiliser la ceinture ?", "a": "Placez-la autour du bas-ventre, réglez la chaleur et laissez agir 20 à 30 min." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, suivi par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre exclusive – stock limité, réservé aux premières commandes !"
    },
    15: {
        "id": 15,
        "name": "Moulinex blender 8 en 1",
        "price": 35000,
        "oldPrice": 65000,
        "stock": 5,
        "category": "Maison",
        "images": ["images/moulinex.png"],
        "img1": "images/mou1.jpg",
        "img2": "images/mou2.jpg",
        "img3": "images/mou3.jpg",
        "img4": "images/mou4.jpg",
        "img5": "images/mou5.jpg",
        "img6": "images/default.jpg",
        "imgCentered": "images/mou5.jpg",
        "title1": "⚡ Moulinex Bardefu 8-en-1 : puissance ultime !",
        "desc1": "Avec ses 9500W et sa capacité de 4L, ce blender multifonction vous permet de préparer jus, smoothies, viande hachée et légumes en quelques secondes.",
        "list1": "⚡ Puissance 9500W\n🍹 8 fonctions\n🥩 Hache viande\n🥤 Smoothies",
        "title2": "🍹 Mixez, hachez, broyez sans effort !",
        "desc2": "Le Moulinex Bardefu 8-en-1 est conçu pour simplifier votre quotidien. Lames puissantes, multifonction ultra pratique, gagnez un temps précieux.",
        "list2": "🍹 Mixage puissant\n🥩 Hache la viande\n🥤 Smoothies onctueux\n⏱️ Gain de temps",
        "title3": "🔥 Le blender qui remplace plusieurs appareils !",
        "desc3": "Pourquoi acheter plusieurs machines quand une seule peut tout faire ? Performance, rapidité et efficacité pour des repas faits maison.",
        "list3": "⚡ 8-en-1\n💪 Performance\n⏱️ Rapidité\n🍽️ Repas maison",
        "video": "videos/mou.mp4",
        "reviews": [
            { "stars": 5, "text": "Très puissant, je l'utilise tous les jours. Mixe parfaitement les fruits congelés.", "author": "Koffi A., Lomé" },
            { "stars": 4.5, "text": "Les 8 fonctions sont vraiment utiles. Je gagne un temps fou.", "author": "Nadia B., Cotonou" },
            { "stars": 5, "text": "Parfait pour jus et smoothies. Le bol en verre est résistant.", "author": "Esso S., Kara" },
            { "stars": 5, "text": "Je recommande vivement. Le moteur 1200W ne bronche pas.", "author": "Jean-Marc D., Sokodé" },
            { "stars": 4.5, "text": "Rapport qualité/prix imbattable. Les accessoires sont nombreux.", "author": "Yves K., Atakpamé" },
            { "stars": 5, "text": "Mon meilleur achat cuisine. Je l'utilise pour soupes, smoothies, pâte.", "author": "Moussa T., Dapaong" },
            { "stars": 5, "text": "Facile à nettoyer, les lames se démontent.", "author": "David H., Lomé" },
            { "stars": 4.5, "text": "Très bon produit. Seul reproche : le manuel est en anglais.", "author": "Rachel M., Tsévié" },
            { "stars": 5, "text": "Pack 2 économique, j'en ai offert un à ma sœur.", "author": "Adama C., Kpalimé" },
            { "stars": 5, "text": "Je l'ai depuis 3 mois, toujours aussi performant.", "author": "Elom G., Aného" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison gratuite partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours." },
            { "q": "Comment utiliser le blender ?", "a": "Placez les ingrédients dans le bol, fermez le couvercle, sélectionnez la vitesse." },
            { "q": "Les pièces sont-elles faciles à nettoyer ?", "a": "Oui, les lames se démontent et passent à l'eau savonneuse." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, suivi par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre exclusive – stock limité, réservé aux premières commandes !"
    },
    16: {
        "id": 16,
        "name": "Crème cindynal réparation intense",
        "price": 10000,
        "oldPrice": 18000,
        "stock": 22,
        "category": "Beauté",
        "images": ["images/talon.jpg"],
        "img1": "images/cin1.jpg",
        "img2": "images/cin2.jpg",
        "img3": "images/cin3.jpg",
        "img4": "images/cin4.jpg",
        "img5": "images/cin5.jpg",
        "img6": "images/default.jpg",
        "imgCentered": "images/cin5.jpg",
        "title1": "👣 Dites stop aux talons craquelés et aux mains abîmées !",
        "desc1": "Le froid, la poussière et le manque d'hydratation agressent votre peau chaque jour. La crème Cindynal répare et protège durablement.",
        "list1": "👣 Répare les talons\n🖐️ Adoucit les mains\n💧 Hydrate intensément\n✨ Peau douce",
        "title2": "🌿 Réparez votre peau sèche et retrouvez une peau douce !",
        "desc2": "Vous souffrez de mains sèches, talons fissurés ou peau rugueuse ? La crème Cindynal réduit les fissures et hydrate intensément.",
        "list2": "🌿 Hydratation intense\n💧 Réduit les fissures\n🖐️ Peau douce\n✨ Résultats visibles",
        "title3": "⚡ Le soin hydratant que votre peau va adorer !",
        "desc3": "Plus besoin de cacher vos mains ou vos pieds à cause de la sécheresse. Application simple matin et soir, résultats visibles dès les premiers jours.",
        "list3": "⚡ Application simple\n💧 Hydratation intense\n✨ Peau douce\n🌿 Naturel",
        "video": "videos/cin.mp4",
        "reviews": [
            { "stars": 5, "text": "Incroyable, mes talons crevassés ont disparu en 3 jours.", "author": "Koffi A., Lomé" },
            { "stars": 4.5, "text": "Sent bon, pénètre vite. Résultat visible après une semaine.", "author": "Nadia B., Cotonou" },
            { "stars": 5, "text": "Efficace contre les crevasses. Ma mère en est ravie.", "author": "Esso S., Kara" },
            { "stars": 5, "text": "Je recommande, très bonne crème. La texture est riche mais non grasse.", "author": "Jean-Marc D., Sokodé" },
            { "stars": 4.5, "text": "Hydrate bien, résultat visible. Je l'utilise aussi sur les coudes.", "author": "Yves K., Atakpamé" },
            { "stars": 5, "text": "Livraison rapide, produit conforme. J'ai pris le pack 2.", "author": "Moussa T., Dapaong" },
            { "stars": 5, "text": "Ma peau rugueuse est devenue lisse. Cette crème est magique.", "author": "David H., Lomé" },
            { "stars": 4.5, "text": "Très bon rapport qualité/prix. Le tube est facile à transporter.", "author": "Rachel M., Tsévié" },
            { "stars": 5, "text": "Pack 2 économique. Un à la maison, un au bureau.", "author": "Adama C., Kpalimé" },
            { "stars": 5, "text": "Je rachèterai. Service client sérieux. La crème sent très bon.", "author": "Elom G., Aného" }
        ],
        "faq": [
            { "q": "Livraison gratuite ?", "a": "Oui livraison gratuite partout à Lomé et 500f à l'intérieur du pays (Togo)." },
            { "q": "Paiement à la livraison ?", "a": "Oui Paiement à la livraison (cash, Mobile Money, carte)." },
            { "q": "Garantie satisfait ou remboursé ?", "a": "Oui, sous 30 jours." },
            { "q": "Comment appliquer la crème ?", "a": "Appliquez matin et soir sur les zones sèches en massant doucement." },
            { "q": "Convient aux peaux sensibles ?", "a": "Oui, testée dermatologiquement. Formule douce sans ingrédients agressifs." },
            { "q": "Puis-je suivre ma commande ?", "a": "Oui, suivi par SMS." }
        ],
        "hidden": false,
        "urgence": "🔥 Offre exclusive – stock limité, réservé aux premières commandes !"
    }
};

// ⚡ Exporter pour une utilisation dans d'autres scripts
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ALL_PRODUCTS;
}